<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ShipGame.Shared\ShipGame.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiteNetLib" Version="2.1.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
